'use client'

import { motion } from 'framer-motion'
import { TrendingUp, PieChart, Share2, AlarmCheck } from 'lucide-react'

const FUNNEL = [
  { label: 'Leads Generated', val: '2,841', pct: 100, color: '#3470F0' },
  { label: 'MQLs Created', val: '847', pct: 72, color: '#C49A3C' },
  { label: 'SQLs Converted', val: '412', pct: 48, color: '#8B5CF6' },
  { label: 'Deals Opened', val: '198', pct: 32, color: '#18B87A' },
  { label: 'Revenue Won', val: '$4.2M', pct: 18, color: '#22C55E' },
]

const REJECTION_REASONS = [
  { reason: 'Not ICP fit', pct: 38, color: '#E0384F' },
  { reason: 'Wrong timing', pct: 27, color: '#F5A623' },
  { reason: 'Already customer', pct: 21, color: '#3470F0' },
  { reason: 'Duplicate lead', pct: 14, color: 'var(--text3)' },
]

const FEATURES = [
  { Icon: TrendingUp, title: 'Pipeline Attribution', desc: 'Total pipeline value generated by marketing-sourced leads — broken down by campaign, channel, and time period.' },
  { Icon: PieChart, title: 'Lead Velocity', desc: 'How quickly leads move from creation → MQL → first meeting. Velocity trends surface bottlenecks before they become pipeline problems.' },
  { Icon: AlarmCheck, title: 'Sales Feedback Loop', desc: 'MQL acceptance and rejection rates by campaign. Rejection reasons categorised and trended — giving Marketing the data to refine the scoring model.' },
  { Icon: Share2, title: 'Marketing Influence Reporting', desc: 'Deals where the account had at least one marketing touchpoint — a more complete picture of marketing\'s contribution to revenue.' },
]

export default function LM_Analytics() {
  return (
    <section id="analytics" style={{ background: 'var(--navy)' }}>
      <style>{`
        .lm-ana-feat {
          display: flex; gap: 14px; align-items: flex-start;
          padding: 14px 18px; border-radius: 14px;
          border: 1px solid transparent; transition: all .28s; cursor: default;
        }
        .lm-ana-feat:hover {
          background: rgba(255,255,255,.04); border-color: rgba(255,255,255,.07);
          transform: translateX(6px);
        }
        .lm-ana-feat-icon {
          width: 38px; height: 38px; border-radius: 10px;
          background: var(--gold-bg); border: 1px solid rgba(196,154,60,.2);
          display: flex; align-items: center; justify-content: center;
          color: var(--gold); flex-shrink: 0; transition: transform .3s;
        }
        .lm-ana-feat:hover .lm-ana-feat-icon { transform: scale(1.1) rotate(-4deg); }
        .lm-funnel-row {
          display: flex; align-items: center; gap: 12px;
          padding: 7px 0; cursor: default;
        }
        .lm-funnel-row:hover { opacity: .85; }
        @media (max-width: 900px) { .lm-ana-cols { grid-template-columns: 1fr !important; } }
      `}</style>

      <div className="wrap">
        <div className="reveal" style={{ marginBottom: 48 }}>
          <div className="eyebrow"><span className="ey-line" />Feature 9 — Lead Attribution &amp; Analytics</div>
          <h2 className="h2">
            Every Lead, Traced Back to Its Source —<br /><em>and Forward to Its Revenue.</em>
          </h2>
          <p className="lead">
            ClientEra doesn't just track leads — it tracks what they become. Every marketing touchpoint is connected to the pipeline value, deal, and revenue it ultimately produced.
          </p>
        </div>

        <div className="reveal lm-ana-cols" style={{
          display: 'grid', gridTemplateColumns: '1.15fr 1fr',
          gap: 48, alignItems: 'start', transitionDelay: '.15s',
        }}>
          {/* LEFT — Funnel + Rejection */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
            {/* Funnel */}
            <div style={{
              background: 'rgba(13,28,52,.88)', backdropFilter: 'blur(22px)',
              border: '1px solid var(--border2)', borderRadius: 16, overflow: 'hidden',
              boxShadow: '0 20px 60px rgba(0,0,0,.4)',
            }}>
              <div className="ce-card-titlebar">
                <span className="ce-wdot ce-wd-r" /><span className="ce-wdot ce-wd-y" /><span className="ce-wdot ce-wd-g" />
                <span className="ce-card-lbl">Pipeline Attribution Funnel — Q1 2026</span>
              </div>
              <div style={{ padding: '16px 18px' }}>
                {FUNNEL.map((f, i) => (
                  <div key={f.label} className="lm-funnel-row">
                    <div style={{ width: 80, fontSize: 10, color: 'var(--text3)', fontWeight: 600, flexShrink: 0 }}>{f.label}</div>
                    <div style={{ flex: 1, height: 22, background: 'rgba(255,255,255,.05)', borderRadius: 5, overflow: 'hidden' }}>
                      <motion.div
                        style={{ height: '100%', borderRadius: 5, background: f.color + 'cc', display: 'flex', alignItems: 'center', paddingLeft: 8 }}
                        initial={{ width: 0 }}
                        whileInView={{ width: `${f.pct}%` }}
                        viewport={{ once: true }}
                        transition={{ delay: i * .1 + .2, duration: .6 }}
                      />
                    </div>
                    <div style={{ fontFamily: "'Fraunces', serif", fontSize: 15, fontWeight: 400, color: f.color, minWidth: 56, textAlign: 'right', flexShrink: 0 }}>{f.val}</div>
                  </div>
                ))}
              </div>
            </div>

            {/* Rejection breakdown */}
            <div style={{
              background: 'rgba(13,28,52,.88)', border: '1px solid var(--border2)', borderRadius: 14, padding: '18px 20px',
            }}>
              <div style={{ fontSize: 9, fontWeight: 700, textTransform: 'uppercase', letterSpacing: 1.2, color: 'var(--text3)', marginBottom: 14, display: 'flex', alignItems: 'center', gap: 8 }}>
                <PieChart size={13} style={{ color: 'var(--gold)' }} />MQL Rejection Reasons
              </div>
              {REJECTION_REASONS.map((r, i) => (
                <div key={r.reason} style={{ marginBottom: 10 }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 4 }}>
                    <span style={{ fontSize: 11, fontWeight: 600, color: 'var(--text2)' }}>{r.reason}</span>
                    <span style={{ fontSize: 12, fontWeight: 700, color: r.color }}>{r.pct}%</span>
                  </div>
                  <div style={{ height: 7, borderRadius: 4, background: 'rgba(255,255,255,.05)', overflow: 'hidden' }}>
                    <motion.div
                      style={{ height: '100%', borderRadius: 4, background: r.color + '50', border: `1px solid ${r.color}30` }}
                      initial={{ width: 0 }}
                      whileInView={{ width: `${r.pct}%` }}
                      viewport={{ once: true }}
                      transition={{ duration: .6, delay: i * .1 }}
                    />
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* RIGHT — Features */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
            {FEATURES.map((f, i) => (
              <motion.div
                key={f.title}
                className="lm-ana-feat"
                initial={{ opacity: 0, x: 16 }}
                whileInView={{ opacity: 1, x: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * .1 }}
              >
                <div className="lm-ana-feat-icon">
                  <f.Icon size={20} strokeWidth={2} />
                </div>
                <div>
                  <div style={{ fontSize: 14, fontWeight: 600, color: 'var(--text)', marginBottom: 4 }}>{f.title}</div>
                  <div style={{ fontSize: 12.5, color: 'var(--text2)', lineHeight: 1.6 }}>{f.desc}</div>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </div>
    </section>
  )
}
